l_simp_chinese: 
  #modifier_building_group_bg_coal_mining_throughput_mult:0 "$bg_coal_mining$[concept_throughput]"
  # modifier_building_group_bg_coal_mining_throughput_mult_desc:0 "对$bg_coal_mining$投入和产出的增益或惩罚"
  modifier_building_group_bg_rubber_throughput_mult:0 "$bg_rubber$[concept_throughput]"
  modifier_building_group_bg_rubber_throughput_mult_desc:0 "对$bg_rubber$投入和产出的增益或惩罚"
  modifier_building_group_bg_whaling_throughput_mult:0 "$bg_whaling$[concept_throughput]"
  modifier_building_group_bg_whaling_throughput_mult_mult_desc:0 "对$bg_whaling$投入和产出的增益或惩罚"
 
 
  # Monetary System group
  institution_ce_treasury:0 "财政与信贷"
  institution_ce_treasury_desc:0 "这一部门囊括发行货币、管控国民经济的健康、税收、调控股票市场和以及国家金融管理等多种业务。"
  modifier_country_institution_ce_treasury_max_investment_add:0 "最大$institution_ce_treasury$[concept_institution]投入等级"
  modifier_country_institution_ce_treasury_max_investment_add_desc:0 "对$institution_ce_treasury$[concept_institution]的最大投入等级的增益或惩罚"
  
  modifier_country_subsidies_bg_light_industry:0 "可以补贴$bg_light_industry$"
  modifier_country_subsidies_bg_light_industry_desc:0 "对$bg_light_industry$实施政府补贴的合法权力"
  modifier_country_subsidies_bg_oil_extraction:0 "可以补贴$bg_oil_extraction$"
  modifier_country_subsidies_bg_oil_extraction_desc:0 "对$bg_oil_extraction$实施政府补贴的合法权力"
  lawgroup_ce_monetary_system:0 "货币体系"
  lawgroup_ce_monetary_system_desc:0 "我国货币的价值是否存在源头，究竟为何物。"
  law_ce_no_monetary_system:0 "无法定通货"
  law_ce_no_monetary_system_desc:0 "这个国家没有货币体系，也没有成文规定并通行的一般等价物（例如香烟、贝壳钱、粮食本位），或者因为他们不需要，或者因为不符合他们的价值观。"
  law_ce_goods_standard:0 "商品本位"
  law_ce_goods_standard_desc:0 "本国货币或一般等价物的价值锚定于一种或多种价值稳定的商品。"
  law_ce_coins:0 "金属货币"
  law_ce_coins_desc:0 "以一种或多种金属作为货币材料，充当一般等价物的货币。同时不同材料的币种还可以根据其原价和重量等比进行兑换。"
  law_ce_silver_standard:0 "银本位"
  law_ce_silver_standard_desc:0 "以白银作为一般等价物，我们的货币锚定于国际、国内银价。在这种货币体系下，商品和劳动力在市场上的实际价格的涨落围绕银价展开。"
  law_ce_gold_standard:0 "金本位"
  law_ce_gold_standard_desc:0 "以黄金作为一般等价物，我们的货币锚定于国际、国内金价。在这种货币体系下，商品和劳动力在市场上的实际价格的涨落围绕金价展开。"
  law_ce_credit_standard:0 "信用货币"
  law_ce_credit_standard_desc:0 "商品价值在纷繁复杂的市场交易中已经完全不能用固定商品的价值来锚定。现代货币采取的信用货币模式将价值直接和企业、社区乃至国家的生产消费能力挂钩。彻底地将货币从商品价格的附庸转化为单独一种商品。"
  law_ce_labour_standard:0 "工分和绩效"
  law_ce_labour_standard_desc:0 "现代资本再生产的核心就是按工作时间进行结算的工资制度，因此我们可以将工时量化为货币使用。这种系统现代社会普遍存在，但是规模有限。例如工分制度、企业KPI、0小时雇佣制或其他类似的绩效考核制度。"
  law_ce_advanced_labour_standard:0 "生产力本位"
  law_ce_advanced_labour_standard_desc:0 "货币的根本作用是作为商品价值的量化单位。因此，它应当反应真正构成商品单位价值的事物——即人类将自然物质转化为商品时所锤入其中的劳动量。劳动量的计算方法有许多，学术上最为著名的就是“社会一般劳动时间”。总的来说，以生产力作为价值的计算方法有助于解决因为个人财富积累不均衡而带来的不平等问题。而一个成功的生产力本位货币体系，也应当考虑生产力发展后劳动质量提升而劳动时间减少的情况。"
 
  # Legal system
  institution_ce_national_church:0 "宗教组织"
  institution_ce_national_church_desc:0 "宗教组织，宗教徒因共同的宗教信仰而结成的社会组织。 古代的部落宗教以及由部落宗教改革发展而来的民族宗教，一般与其存在的社会融为一体，没有独立的组织。 后来由个人创立的人为宗教，一般都有其独立于社会的教派组织。 "
  modifier_country_institution_ce_national_church_max_investment_add:0 "最大$institution_ce_national_church$[concept_institution]投入等级"
  modifier_country_institution_ce_national_church_max_investment_add_desc:0 "对$institution_ce_national_church$[concept_institution]的最大投入等级的增益或惩罚"
  
  lawgroup_ce_legal_system:0 "法律体系"
  lawgroup_ce_legal_system_desc:0 "立法的原则，秩序的基石。"
  law_ce_customary_law:0 "习惯法"
  law_ce_customary_law_desc:0 "在法律学中，习惯法并无唯一一个准确定义。习惯法可以指原住民和当地社区固有的习俗或生活方式，又可以是指原住民和当地社区的法律、规则实践和习俗。"
  law_ce_morale_code:0 "道德规范和宗教法"
  law_ce_morale_code_desc:0 "宗教法系指基于宗教传统而导出的道德及伦理准则。法律中的宗教含义是不可易的，因为神的话语是不可以被决官或政府修改或制定的。"
  law_ce_natural_law:0 "自然法"
  law_ce_natural_law_desc:0 "自然法，为独立于政治上的实在法而存在的正义体系。对它的诠释与使用在历史上千差万别。通常而言，自然法的意义包括道德理论与法学理论。"
  law_ce_no_legal_system:0 "不设法律体系"
  law_ce_no_legal_system_desc:0 "我们认为法律实际上是有组织的压迫，是对人的自然状态的侵犯。在我们的社会中不需要法律规范。"
  law_ce_civil_law:0 "民法法系"
  law_ce_civil_law_desc:0 "又称为“大陆法系”，顾名思义，采纳民法法系的国家通常都有完整、独立的民法典。除此以外，民法法系管理下，大多数法律种类都将编纂成册，在各法律领域发布“法典”。"
  law_ce_common_law:0 "普通法系"
  law_ce_common_law_desc:0 "俗称“海洋法系”，发源自不列颠及其殖民地。普通法系的特点就是判例法，即反复参考判决先例，最终产生类似道德观念一般的普遍的、约定俗成的法律。"
  law_ce_militaized_law:0 "法律军事化"
  law_ce_militaized_law_desc:0 "法律作为统治工具的作用在这一体系中发挥到极致。严苛的局势迫使我们将战争的条例和纪律注入到社会当中。"
  law_ce_peoples_law:0 "人民法系"
  law_ce_peoples_law_desc:0 "随着人类社会的进一步发展。我们认识到真正属于社会和人民的法律体系应当是不断受到挑战并进步的，并维护我国最广大阶级群众利益的体系。简单来说，法律不应当像封建大家长那样以绝对的权威规训人民，它应当成为人民操作国家和社会机器的帮助手册。"
  
  # Judicial System
  institution_ce_judicial_court:0 "法院"
  institution_ce_judicial_court_desc:0 "行驶司法权的行政机关。一般情况下只是调解和裁决民众间纷争的机构，但实际上它的作用取决于各次审判所涉及的社会领域和案件自身的性质。"
  modifier_country_institution_ce_judicial_court_max_investment_add:0 "最大$institution_ce_judicial_court$[concept_institution]投入等级"
  modifier_country_institution_ce_judicial_court_max_investment_add_desc:0 "对$institution_ce_judicial_court$[concept_institution]的最大投入等级的增益或惩罚"
  lawgroup_ce_judicial_system:0 "司法机关"
  lawgroup_ce_judicial_system_desc:0 "司法机关是行使司法权的国家机关，是国家机构的基本组成部分，是依法成立的行使相关国家职权的司法组织。"
  law_ce_local_court_system:0 "地方法院"
  law_ce_local_court_system_desc:0 "不设立法定审判机关，司法权的解释和行使由我们国家各个地区、部落、社区或是其他自治实体自行判断。"
  law_ce_national_court_system:0 "国家法院"
  law_ce_national_court_system_desc:0 "由某一类官僚运行的，有等级秩序并高度组织化的政府司法机关。"
  law_ce_supreme_court_system:0 "最高法院体系"
  law_ce_supreme_court_system_desc:0 "以最高法院为核心的司法检察体系。最高法院是最高级的司法机构，通常有对诉讼的最终审判权（即不可推翻的）和对法律（包括宪法）的最终解释权，但实际权力及名称在各地不尽相同。"
  law_ce_privatised_court_system:0 "私有法院"
  law_ce_privatised_court_system_desc:0 "将我国的司法权承包给负责任的私人企业执行。国家仅行使检察和监督权以“保证“权力不被滥用。"
  law_ce_revolutionary_court_system:0 "革命法庭"
  law_ce_revolutionary_court_system_desc:0 "为了消除旧社会的影响，我们应当亮出法制体系作为暴力工具的一面。"
 
  # Events
 ce_debate_events.1.t:0 "增长超预期"
 ce_debate_events.1.d:0 "中央经济办公室宣布，我们将经济事务纳入政府控制的工作导致了惊人的经济正增长。"
 ce_debate_events.1.f:0 "男人紧张地扶了扶自己的眼镜。“说老实话，我都惊了，”他承认道。“我把数字计算了两遍，又派了三位文员来到办公室检查我的工作，然后你猜怎么着？我们跑到了计划前面，增长率超过了先前的预期！为什么，我想我可以先庆祝一下！”\n\n他用手够到了自己的领结，摸了一会儿，然后将其摘了下来。“看清楚了，世界，我今晚可以放松一下了！”他欢天喜地地哭喊道。"
 ce_debate_events.1.a:0 "非常棒！继续推动法律制定。"
 ce_debate_events.1.b:0 "非常棒！我们应当给让这一切成真的文员们一点支持。"

 ce_debate_events.2.t:0 "党派争端"
 ce_debate_events.2.d:1 "政府的某个派系反对我们改变经济政策的步调和手段，希望能就此讨论，并让我们修正当前的议程。"
 ce_debate_events.2.f:0 "“尽管我知道，有人控诉我就是个唱唱反调的人，但我能向今天在座的每一个人保证我忠于自己的党派。我想说的是，朋友们，我们的政策是否已经酝酿的足够成熟，使得我们已经可以完全放弃过时的那套社会经济系统。”"
 ce_debate_events.2.a:0 "让党派成员们就这个议题展开辩论。"
 ce_debate_events.2.b:0 "在党派大会上表明我们的立场。"
 ce_debate_events.2.c:0 "同反对派私下里聊一聊。"

 ce_debate_events.3.t:0 "胜利冲昏头脑"
 ce_debate_events.3.d:0 "我们全方位地推进经济改革的工作，在[SCOPE.sState('state_run_state').GetName]造成了物资短缺和管理混乱。"
 ce_debate_events.3.f:0 "“这是事实，我们已经过度完成了我们规划的经济改革，我们在[SCOPE.gsInterestGroup('command_econ_proponent_ig').GetNameNoFormatting]的朋友们被胜利冲昏了头脑，此时此刻失去了明晰的头脑和清醒的眼界。”"
 ce_debate_events.3.a:0 "我们必须承认自己的错误。"
 ce_debate_events.3.b:0 "我们没有失败，赢麻了！"

 ce_debate_events.4.t:0 "不合理的敲诈"
 ce_debate_events.4.d:1 "一名来自[SCOPE.gsInterestGroup('pro_free_trade_ig').GetName]的演说家正在全国范围内作巡游演讲，诋毁[SCOPE.sLawType('standing_law_scope').GetName]并赞扬自由贸易的价值。"
 ce_debate_events.4.f:0 "“当我们认识到，我们伟大系统的理论能够保证每个人都能充分享受工业与企业带来的成果，我们就很清楚，除了商品的自由流通以外，任何其他事情都是不合理的敲诈和对我们价值观的有罪被判。”"
 ce_debate_events.4.a:0 "我们朝着共同的目标艰苦奋斗！"
 ce_debate_events.4.b:0 "[SCOPE.gsInterestGroup('pro_free_trade_ig').GetName]可真是一个引人注目的演说家。"

 ce_debate_events.5.t:0 "理念的市场"
 ce_debate_events.5.d:0 "反对我们规划的经济改革的人要求他们的理念应该同我们自己的一样得到反映，此外，他们还特别阴阳怪气地用我们的自由市场腔调为自己的发言权正名。"
 ce_debate_events.5.f:0 "“我们唯一诉求的就是自由流通……理念的自由流通。”"
 ce_debate_events.5.a:0 "我们要的是自由市场，不是信口开河！"
 ce_debate_events.5.b:0 "竞争是必要的，哪怕是理念层面。"
 ce_debate_events.5.c:0 "狭路相逢，持真理者胜！"

 ce_debate_events.6.t:0 "[SCOPE.sState('industrial_protectionist_state').GetName]的工业损害"
 ce_debate_events.6.d:0 "来自海外的竞品导致了对[SCOPE.sState('industrial_protectionist_state').GetName]产品需求量的下降，这些事情在该地区引发了人们对我们规划的改革的担忧。"
 ce_debate_events.6.f:0 "“自由的外国贸易能够给我们金钱，然而让我们的市场对其他人开放，会损害我们的劳工，我们的工业，以及我们的人民。如果这些政策不能让我们受益，它们的好处又在哪里呢？”"
 ce_debate_events.6.a:0 "我们必须缓解[SCOPE.sState('industrial_protectionist_state').GetName]的担忧。"
 ce_debate_events.6.b:0 "我们必须让[SCOPE.sState('industrial_protectionist_state').GetName]相信我们改革的优点。"
 ce_debate_events.6.c:0 "不论如何我们都要向前推动我们的规划。"
 
 ce_debate_events.7.t:0 "事迹宣传"
 ce_debate_events.7.d:0 "无政府主义者宣布对一处绅士俱乐部的炸弹袭击事件负责，此处有许多[SCOPE.gsInterestGroup('anarchy_target_ig').GetName]的成员频繁造访。人们在瓦砾中找到了[SCOPE.sCharacter('anarchy_target_leader').GetFullName]的尸体。"
 ce_debate_events.7.f:0 "“战争，阶级战争，而你才是第一个在名为秩序的权力机构的掩护下、在你的法律的黑暗处发动这场战争的人。会有流血；我们不会逃避；会有谋杀：我们会下杀手，因为那是必要的；会有毁灭；我们会亲手毁灭你的暴政机器营造的世界。”" #Luigi Galleani
 ce_debate_events.7.a:0 "这些反动派活该。"
 ce_debate_events.7.b:0 "我们不能宽恕恐怖主义。"
 
 ce_debate_events.8.t:0 "废除国家"
 ce_debate_events.8.desc:0 "趁着[ROOT.GetCountry.GetName]走向[SCOPE.sLaw('current_law_scope').GetName]的东风，[SCOPE.gsInterestGroup('anarchists_scope').GetName]呼吁废除国家机构。"
 ce_debate_events.8.f:0 "“我们怎么能一边维持国家的暴政，一边称自己为无政府社会呢？国家暴力的作恶者仍在我们中间横行；警察、征兵官、殖民管理者——都是些阶级叛徒。他们窃取我们诚实劳动的果实，将之用来压迫我们！”"
 ce_debate_events.8.a:0 "取缔警察！"
 ce_debate_events.8.c:0 "国家无权控制我们！"
 ce_debate_events.8.d:0 "殖民就是对人类的祸害！"
 ce_debate_events.8.e:0 "国家将缓慢地消亡。"

 
 ce_debate_events.9.t:0 "互助"
 ce_debate_events.9.d:0 "无政府主义者正在创建一种摒弃利润，将帮助人类同胞视为共同责任的社群。[SCOPE.gsInterestGroup('farmer_ig').GetName]的新领袖[SCOPE.sCharacter('anarchist_farmer').GetFullName]就一直在鼓励建立合作农场。"
 ce_debate_events.9.f:0 "“我们不需要地主，不需要老板，甚至不需要国家。共同劳动，我们就能提供我们所需的一切，自由而平等地生活，我们每个人都依赖于社群的福祉，同时也都为社群福祉负责。”"
 ce_debate_events.9.a:0 "我们团结在一起会更强大。"
 ce_debate_events.9.c:0 "这会事很好的宣传。"
 ce_debate_events.9.b:0 "他们对农业有一套十分吸引人的手段。"
 
 ce_debate_events.10.t:0 "过去之罪"
 ce_debate_events.10.d:0 "[SCOPE.sLaw('current_law_scope').GetName]改革的支持者唤起了公众对现政府过去滥用权力的关注，这也是迫切需要改革的原因之一。"
 ce_debate_events.10.f:0 "“啊，我都快记不得了。那是个不一样的年代。这种事就那么发生了，从没想到还会有人质询我。这并不是说它毫无争议，但抱怨者什么时候都有。想办成事就不能听他们的。当然，这都得到了[ROOT.GetCountry.GetRuler.GetPrimaryRoleTitle]的批准。不是明面上的，不过我觉得你应该知道。别告诉别人。”"
 ce_debate_events.10.a:0 "权力导致腐败，这就是为什么掌权者必须对选民负责。"
 ce_debate_events.10.b:0 "过去的事就过去了。这些问题与改革无关。"
 
 ce_debate_events.11.t:0 "嘴上没毛"
 ce_debate_events.11.d:0 "新的[SCOPE.sLaw('current_law_scope').GetName]改革还在进行当中。但最近却爆发了一次引人注目的青少年犯罪事件，由于在现行法律体系下，青年选民和少年犯都缺乏一定之规。一场关于[ROOT.GetCountry.GetName]政治责任年龄的讨论迅速席卷了社会各界。\n\n当然，最重要的是——在这次改革中，少年人们的意见究竟是负担还是分量？"
 ce_debate_events.11.f:0 "“我的父母都不识字，不过我哥哥识字，更重要的是，他有阅读的习惯。他上次从大学回家，问我对誓死捍卫[ROOT.GetCountry.GetNameNoFormatting]文明社会的责任感有什么感触。然后他告诉我新的法律改革，并问我是否考虑过我对[ROOT.GetCountry.GetNameNoFormatting]应该有什么责任。我觉得他提出了一个令人信服的论点——而如果我够年龄投票，或者是承担自己的权力和义务，分辨对错，他肯定也够。”"
 ce_debate_events.11.a:0 "投票年龄设立在25岁，法定成年年龄也当如此。"
 ce_debate_events.11.b:0 "21岁似乎是合理的折中。"
 ce_debate_events.11.c:0 "18岁就算是成年了。"
 
 ce_debate_events.12.t:0 "争论的文书工作"
 ce_debate_events.12.d:0 "即将到来的[SCOPE.sLaw('current_law_scope').GetName]改革将极大震动我们的国体。从更易法典到腾挪办公楼房，抑或是倾听或压制中外争辩之音，这次改革对[ROOT.GetCountry.GetAdjectiveNoFormatting]政府的行政能力造成了很大压力。更别提还要依照我们的舆情和政体整理公众的意见和讨论了。"
 ce_debate_events.12.f:0 "“等到整个基础架构到位就容易得多了。我们需要证明我们能做到。人民需要相信他们的意见正在被被正确地收集和统计，不然他们很快就会认为选举是一场骗局。人民在看着，其他国家也在看着。我们不能走捷径。”"
 ce_debate_events.12.a:0 "如果有必要的话，我们将动用其他行政部门的资源。"
 ce_debate_events.12.b:0 "我们只需要慢慢来。"
 administrative_assistance_for_elections_1:0 "为民意收集提供行政援助"
 setting_up_election_system_1:0 "倾听民心"
 
 ce_debate_events.13.t:0 "魅力非凡的演讲"
 ce_debate_events.13.d:0 "一位尤其有魅力的政治学者就[ROOT.GetCountry.GetCapital.GetCityHubName]中[SCOPE.sLaw('current_law_scope').GetName]的益处发表了一次演讲，反响极其热烈。"
 ce_debate_events.13.f:1 "“资本家、旧官员和腐败分子的发动机燃烧的是我们的血汗，而谁看见了收益？不是我们，不是！一位穿着高帽和精美的鞋子，并且在[SCOPE.sCountry('holiday_home_country').GetCapital.GetCityHubName]有度假房屋的人，喝着最上佳的美酒，而我们则卑躬屈膝，只为了一点残渣。”"
 ce_debate_events.13.a:0 "说得好，他们应该多说点！"
 ce_debate_events.13.b:0 "也许他们的天生魅力可以激发些许忠诚。"

 ce_debate_events.14.t:0 "微型革命"
 ce_debate_events.14.d:0 "一组工人据说起义反抗他们的上级，控制了[ROOT.GetCountry.GetCapital.GetCityHubName]的工厂。"
 ce_debate_events.14.f:0 "“有一天，他们跑进来把秘书和保安扔了出去，摔了个底朝天，然后继续照常工作。警察试图介入，但那是在给几百名挥舞着工具的工厂工人下令要做什么。”"
 ce_debate_events.14.a:0 "我们静观其变。"
 ce_debate_events.14.b:0 "我们需要停止这种事。"

 ce_debate_events.15.t:0 "党部被烧毁"
 ce_debate_events.15.d:0 "共产党的一个支部被烧毁了。由此造成的组织损失严重妨碍了他们的发展。"
 ce_debate_events.15.f:0 "“亲爱的@censored!@censored!@censored!@censored!同志，我很遗憾地通知你，由于大火焚毁了大部分建筑，我们位于@censored!@censored!@censored!@censored!街的党支部已无法运行。我们怀疑这是@censored!@censored!@censored!@censored!犯下的暴行，但目前还没有证据。”"
 ce_debate_events.15.a:0 "坏消息。"
 ce_debate_events.15.b:0 "我确信我们能在某处安置他们。"
 
 ce_debate_events.16.t:0 "离奇失踪"
 ce_debate_events.16.d:0 "鉴于[SCOPE.gsInterestGroup('anti_secret_police_ig').GetName]的[SCOPE.sCharacter('anti_secret_police_leader').GetFullName]最近对[SCOPE.sLaw('current_law_scope').GetName]的反对，[SCOPE.sCharacter('anti_secret_police_leader').GetHerHis]的失踪引起了精英们的严重担忧。"
 ce_debate_events.16.f:1 "“当其家人向有关部门报告时，已经过了中午：[SCOPE.sCharacter('anti_secret_police_leader').GetFullNameNoFormatting]已经失踪了一整晚，没有警告或纸条留下。亲属们认为这很可能与[SCOPE.sCharacter('anti_secret_police_leader').GetHerHis]坚持反对[SCOPE.sLaw('current_law_scope').GetName]有关，因为前几天有人在门口放了一把小刀，他们现在觉得那应该是一种威胁。”"
 ce_debate_events.16.a:0 "这里没什么好调查的。"
 ce_debate_events.16.b:0 "我们不能以人民的信任为代价通过法律。"
 
 ce_debate_events.17.t:0 "偶然发现"
 ce_debate_events.17.d:0 "就在政府准备通过[SCOPE.sLaw('current_law_scope').GetName]法时，我们的特工抓到了一个[SCOPE.sC('spy_country').GetAdjectiveNoFormatting]间谍，这破坏了我们对他们本就微弱的信任。"
 ce_debate_events.17.f:1 "“我们所有将军和他们家人的名单，我们兵营和港口情况的记录，我们进出口、生产、港口、一切的预测！我甚至很惊讶他们没搞到我们最喜爱的[SCOPE.GetRootScope.GetCountry.GetCustom('alcohol')]的清单。”"
 ce_debate_events.17.a:0 "我们的人民需要知道！"
 ce_debate_events.17.b:0 "这是一份非常有用的信息，应该保持……私密。"
 
 ce_debate_events.18.t:0 "信息时代"
 ce_debate_events.18.d:0 "随着[SCOPE.sLaw('current_law_scope').GetName]法律获得关注，许多人都表达了对言论自由的担忧。"
 ce_debate_events.18.f:0 "“我有权不存在！”一名忧心忡忡的公民这么对《[SCOPE.GetRootScope.GetCountry.GetCustom('generic_newspaper_type')]》说。“这是闻所未闻的——暴行！万一信息不准确……想象一下，仅仅是因为他们把你列入了错误的名单，搞错了你的意识形态和背景，你就被指控犯有一项你根本没犯的罪行。”"
 ce_debate_events.18.a:0 "他们说的似乎有道理。"
 ce_debate_events.18.b:0 "他们没什么好担心的！"
 
 ce_debate_events.21.d:0 "随着[SCOPE.sLaw('current_law_scope').GetName]法律获得关注，许多人都表达了对隐私的担忧。"
 ce_debate_events.21.f:0 "“私企无权对我施行审判，抑或是查看我的公民信息！”一名忧心忡忡的公民这么对《[SCOPE.GetRootScope.GetCountry.GetCustom('generic_newspaper_type')]》说。“这是闻所未闻的——暴行！万一信息被私下拍卖，或者不准确！……想象一下，仅仅是因为你没钱雇佣一个好律师，或者没钱购买会员，或者他们的员工加班太晚意识模糊，你就被指控犯有一项你根本没犯的罪行！”"
 ce_debate_events.25.t:0 "繁琐手续"
 ce_debate_events.25.d:0 "公务员队伍在[SCOPE.gsInterestGroup('bureaucrat_class').GetName]的领导下，通过制造毫无必要的文书工作故意拖延政府运转。他们要求自己的岗位在[SCOPE.sLaw('current_law_scope').GetName]法律下得到保护。"
 ce_debate_events.25.f:0 "“我很乐意帮忙，但是很遗憾，这张申请表只盖了两次章。你得找地区调查员投诉，但他目前正忙着优化我们的新归档系统。你会在六到八个月内得到快速答复。”"
 ce_debate_events.25.a:0 "现在的公务员能保住他们的位置。"
 ce_debate_events.25.b:0 "不可接受！回去干活儿。"
 ce_debate_events.25.c:0 "秘密警察会让他们守规矩的。"
 red_tape:0 "繁琐手续"
 red_tape_reduced:0 "减少繁琐手续"
 red_tape_jobs:0 "官僚主义老油条"
 ce_debate_events.26.t:0 "任人唯贤"
 ce_debate_events.26.d:0 "新的[SCOPE.gsInterestGroup('meritocracy_ig').GetName]官僚在每个方面都做得比[SCOPE.gsInterestGroup('bureaucrat_class').GetName]更亮眼。这足可见[SCOPE.sLaw('current_law_scope').GetName]的成效，真是鼓舞人心。"
 ce_debate_events.26.f:0 "“他们觉得自己出身富贵，就理应得到最重要的职位。但他们的特权让他们变得懒惰，变得任人唯亲，变得傲慢。相比之下，我们必须为我们所拥有的一切努力，一旦失败，就会对我们造成切实的影响。晋升应当只看功绩，不看出身。”"
 ce_debate_events.26.a:0 "显然，[SCOPE.sLaw('current_law_scope').GetName]是正确的政策。"
 ce_debate_events.26.b:0 "[SCOPE.gsInterestGroup('bureaucrat_class').GetName]干得实在太差劲了。"
 ce_debate_events.26.c:0 "鼓励[SCOPE.gsInterestGroup('meritocracy_ig').GetName]加入行政部门。"
 meritocracy:0 "任人唯贤"
 meritocracy_ig:0 "任人唯贤"
 ce_debate_events.27.t:0 "官僚斗争"
 ce_debate_events.27.d:0 "我们设法通过[SCOPE.sLaw('current_law_scope').GetName]的努力遭到了几个顽固的官僚老古董的阻挠。某些崇高的问题，比如档案柜的正确形状，引起了异常激烈的讨论。"
 ce_debate_events.27.f:1 "“好，快，省。你只能得到两样。”"
 ce_debate_events.27.a:0 "我们将不惜费用。"
 ce_debate_events.27.b:0 "那就顺其自然吧。"
 ce_debate_events.27.c:0 "让我们赶紧解决吧。"
 ce_debate_events.28.t:0 "擦边而过"
 ce_debate_events.28.d:0 "刺客的子弹今早擦着一名来自[SCOPE.gsInterestGroup('assassination_target_ig').GetName]的大臣而过，这一事态引发了要求迅速通过[SCOPE.sLaw('current_law_scope').GetName]的呼声。[SCOPE.gsInterestGroup('they_dont_like_laws_ig').GetName]是[SCOPE.sLaw('current_law_scope').GetName]的反对派，他们也被指控间接地支持了这场刺杀。"
 ce_debate_events.28.f:0 "“这场险些酿成的惨剧只不过是一系列事故的最新一场。如果我们今天不做点什么，更待何时？在我们采取措施之前，还要有多少人受伤？”"
 ce_debate_events.28.a:0 "我们必须保护好自己。"
 ce_debate_events.28.b:0 "必须对那些反对命令的人予以谴责。"
 ce_debate_events.29.t:0 "纸媒的监督辩论"
 ce_debate_events.29.d:0 "在全国范围内实行[SCOPE.sLaw('current_law_scope').GetName]的努力变成了党派纸媒之间辩论的话题，这有可能扰乱法律制定的进程。"
 ce_debate_events.29.f:0 "“亲爱的编辑，\n\n作为一名普通公民，我毫无疑问同当前全国范围内就这项法律制定与执行的大辩论没有任何关系。我，仅仅只是一名普通公民，想写下一些深思熟虑之后的文字……”"
 ce_debate_events.29.a:0 "就让报纸畅其所言吧。"
 ce_debate_events.29.b:0 "在纸媒上发布我们自己的社论。"
 ce_debate_events.29.c:0 "纸媒在这一事务上已经畅所欲言地足够多了。"
 ce_debate_events.30.t:0 "备受攻讦的集会"
 ce_debate_events.30.d:0 "一场[SCOPE.sPoliticalMovement('rally_movement').GetName]的和平表达集会遭到了当地民兵的粗暴打断。[SCOPE.gsInterestGroup('rally_movement_ig').GetName]，这场运动的主要支持者，对于暴力行径尤其沮丧。这一事件让很多人开始质疑，制定任何法律赋予使用武力的权力，这一举措是否明智。"
 ce_debate_events.30.f:0 "“恶人和屠夫们挥舞着他们的斧头，上面沾染着的无辜者的鲜血已然开始发臭。这就是你想在全国推广的‘正义’？政府必须召集大臣出面给民众一个解释，否则它就得倒台。”"
 ce_debate_events.30.a:0 "或许一段反思期对于现在来说是有必要的。"
 ce_debate_events.30.b:0 "我们不能让类似言论公开——那会破坏[SCOPE.sPoliticalMovement('rally_movement').GetName]的推进。"
 ce_debate_events.30.c:0 "这正是为什么我们需要[SCOPE.sLaw('current_law_scope').GetName]来取代暴力！"
 
 ce_debate_events.34.t:0 "自由的呐喊"
 ce_debate_events.34.d:0 "为了让贬低者闭嘴，[SCOPE.sLaw('current_law_scope').GetName]的支持者组织了一场抗议。然而，警察决定将法律掌握在自己手中，暴力镇压了抗议者。"
 ce_debate_events.34.f:1 "“哈！真是讽刺啊！我们的现行法律未能保护公民权益免受腐败警察的侵害，对旧体制的抗议反而被那些警察镇压了！写这篇文章时，我的手气得发抖。那些警察现在就敢这样，将来要做什么想都不敢想！我们需要如此宪法来保护我们。”"
 ce_debate_events.34.a:0 "双方都需要冷静。"
 ce_debate_events.34.b:0 "警察必须为此公开道歉。"
 
 ce_debate_events.35.t:0 "宪法原则与安全"
 ce_debate_events.35.d:1 "政府成员担心朝向[SCOPE.sLaw('current_law_scope').GetName]前进的改革会危及国家的内部稳定。"
 ce_debate_events.35.f:0 "“根据新的宪法原则，我们获取公众信息将要遭到巨大的困难。这让我们要如何阻止守旧派的攻击和阴谋？如果我们只能给予人民一种虚假的安全感，又如何保护他们的安全？”"
 ce_debate_events.35.a:0 "那些信息对我们的管理至关重要。"
 ce_debate_events.35.b:0 "我们会换成其他不那么有侵入感的方法。"
 
 ce_debate_events.36.t:0 "反动浪潮"
 ce_debate_events.36.d:0 "有人发现警察正有组织地攻击新法律体系的支持者，破坏他们的营业和聚会场所。"
 ce_debate_events.36.f:1 "“他们砸烂了长凳，砸烂了门。向窗户扔石头，烧了所有的书。在墙上涂鸦，把我们描绘成了动物，而他们则统治着我们。他们还留下了一些威胁，所以我们知道那就是他们。”"
 ce_debate_events.36.a:0 "我们应该进行公开讲话，明确表示这是不可接受的。"
 ce_debate_events.36.b:0 "警察集团是旧体制的受益者。必须进行清洗。"
 
 ce_debate_events.37.t:0 "学界的协助"
 ce_debate_events.37.d:0 "我们高等院校的政治学、法学教师提出，他们可以就指定符合[SCOPE.sLaw('current_law_scope').GetName]的新法律体系这一重大改革向政府提供建议。"
 ce_debate_events.37.f:0 "“当然了，我们法律界的学术研讨和制定国家法律体系差距很大。不过，作为知识这座高塔的高层建筑师，我们相信，至少我们对于如何夯实基础还是有一些见解的。”"
 ce_debate_events.37.a:0 "很高兴有他们的帮助！"
 ce_debate_events.37.b:0 "他们的研究工作更加重要。"
 ce_debate_events.38.t:0 "规训与惩戒"
 ce_debate_events.38.d:0 "[SCOPE.gsInterestGroup('armed_forces_ig').GetName]指出了新法律体系中公民教育方面有待改善的地方，认为纪律在新[SCOPE.sLaw('current_law_scope').GetName]中所扮演的角色需要提高。"
 ce_debate_events.38.f:0 "“这不仅仅是保持教室整洁以便教授知识，这还是在培养性格。毕竟，我们承担着这些孩子的父母交给我们的巨大责任，他们竭尽全力希望能将孩子培养成正直的公民。我们经常发现一些服兵役的男孩，其性格已经被青少年时期的不守规矩和对权威缺乏尊重彻底毁了。不能这样！”"
 ce_debate_events.38.a:0 "我们应该专注于课程。"
 ce_debate_events.38.b:0 "将这些纳入学校体系是最优先的。"
 ce_debate_events.39.t:0 "古今异同"
 ce_debate_events.39.d:0 "政府内部对于[SCOPE.sLaw('current_law_scope').GetName]中的民法条文应如何塑造这个国家及其人民的未来产生了一些分歧。尤其是婚姻制度、商法和青少年犯罪等议题讨论异常激烈。有的人主张应当审时度势，“法后王”。而另一些人则认为对方的法律思想过于“现代”，简直是象牙塔里的书生之见。生搬硬套不过是在搞拙劣的社会实验。必然引起社会动荡。也得不到普通群众的支持。"
 ce_debate_events.39.f:0 "“这些民法条文和法案或许很适合两个世纪前的国家，或是世界上别的什么奇妙民族，但相信它们在如今这个时代能框住我们的公民，那简直就是疯了！你这是在我们神圣的法典里书写奴役！”\n“你的意思是你的‘现代司法’更公平正义？你要抛弃现有的生活方式和无数判例？你想摧毁我们的政权吗！”"
 ce_debate_events.39.a:0 "先做一份临时的法典出来！"
 ce_debate_events.39.b:0 "花些时间研究现代判例，体察民情。"
 curriculum_compromise_1:0 "临时约法"
 extended_curriculum_discussions_1:0 "最合适的条文"
 


